LOCK TABLES `commodities_tags` WRITE;
/*!40000 ALTER TABLE `commodities_tags` DISABLE KEYS */;
INSERT INTO `commodities_tags` VALUES
('Adamantine','Armour Component',1),
('Adamantine','Building Material',3),
('Aluminium','Armour Component',1),
('Aluminium','Tech Metal',1),
('Archeotech','Archeotech',1),
('Biomass Chemical','Biomass Chemicals',1),
('Biomass Medical','Biomass Medical',1),
('Books','Teaching Materials',1),
('Books','Luxury Good',1),
('Bricks','Building Materials ',2),
('Carapace','Armour',1),
('Carbon','Carbon',1),
('Ceramic Plates','Armour Component',1),
('Chemicals','Chemicals',1),
('Clay','Clay',1),
('Coal','Fuel',2),
('Copper','Conductor Metal',1),
('Flack','Armour',1),
('Food','Food',2),
('Food','Luxury Goods',1),
('Refined Food','Food',1),
('Gas','Fuel 2',2),
('Gemstones','Gemstones',1),
('Gemstones','Luxury Good',1),
('Gold','Conductor Metal',1),
('Gold','Luxury Good',1),
('Heavy Weapons','Heavy Weapons',1),
('Heavy Munitions','Heavy Munitions',1),
('Prometheum','Fuel 3',3),
('Aviation Fuel','Aviation Fuel',1),
('Iron','Gun Metal',1),
('Iron','Armour Component',1),
('Iron','Building Material 2',2),
('Macromunitions','Macromunitions',1),
('Macroweapons','Macroweapons',1),
('Medicine','Medicine',1),
('Mesh Armour','Armour',1),
('Oil','Fuel 2',2),
('Oxygen','Oxygen',1),
('Plant Machinery','Plant Machinery',1),
('Plastics','Plastics',1),
('Propellant','Propellant',1),
('Rockrete','Building Material',2),
('Rubber','Rubber',1),
('Salt','Preservatives',1),
('Servitors','Labour',1),
('Slaves','Labour',1),
('Small Arms Munitions','Small Arms Munitions',1),
('Small Arms','Small Arms',1),
('Soldiers','Soldiers',1),
('Steel','Building Material',3),
('Steel','Tech Metal',1),
('Steel','Conductor Metal',1),
('Steel','Gun Metal',1),
('Steel','Armour Component',1),
('Stone','Building Materials',2),
('Tech 1','Tech',1),
('Tech 2','Tech',2),
('Tech 3','Tech',3),
('Natural Textiles','Textiles',1),
('Natural Textiles','Luxury Good',1),
('Synthetic Textiles','Textiles',1),
('Titanium ','Armour Component',1),
('Titanium ','Tech Metal',1),
('Vehicles','Vehicles',1),
('Water','Water',1),
('Wood','Fuel 1',1),
('Wood','Building Material 1',1),
('Wood','Writing Medium',1),
('Drudgers','Labour',1),
('Xenotech','Luxury Goods',1),
('Natural Textiles','Writing Medium',1);
UNLOCK TABLES;
