LOCK TABLES `commodities` WRITE;

INSERT INTO `commodities` VALUES('Adamantine'),
('Aluminium'),
('Archeotech'),
('Biomass Chemical'),
('Biomass Medical'),
('Books	'),
('Bricks'),
('Carapace'),
('Carbon'),
('Ceramic Plates'),
('Chemicals'),
('Clay'),
('Coal'),
('Copper'),
('Flack'),
('Food'),
('Refined Food'),
('Gas'),
('Gemstones'),
('Gold'),
('Heavy Weapons'),
('Heavy Munitions'),
('Prometheum'),
('Aviation Fuel'),
('Iron'),
('Macromunitions'),
('Macroweapons'),
('Medicine'),
('Mesh Armour'),
('Oil'),
('Oxygen'),
('Plant Machinery'),
('Plastics'),
('Propellant'),
('Rockrete'),
('Rubber'),
('Salt'),
('Servitors'),
('Slaves'),
('Small Arms Munitions'),
('Small Arms'),
('Soldiers'),
('Steel'),
('Stone'),
('Tech 1'),
('Tech 2'),
('Tech 3'),
('Natural Textiles'),
('Synthetic Textiles'),
('Titanium'),
('Vehicles'),
('Water'),
('Wood'),
('Drudgers'),
('Xenotech');
UNLOCK TABLES;